# Welcome to an introductory R course for natural scientists {.unnumbered}
## One Code To Rule Them All 

This page was originally built to act as an introduction to R and R studio. 
What it has become is that, plus a little extra.
This page will be updated as new information/ lessons are requested. 
The link will not change, so no trouble. 

We suggest starting from the beginning (even if you have used R before) and working through each section. 
When appropriate, previous sections will be referenced, sometimes linked, and we encourage you to use previous sections when needed. 
Along with this, there are snippets of code which we encourage you to give a burn and copy each into your script. 

If you have any suggestions or concerns, please email me at **Jared.Adam@psu.edu**. 


### What this course will cover: 
### Part 1: The Reasoning {.unnumbered}

  - **Introduction:** What is programming and what  is R? 

  - **R as a tool:** How can we use R? 

### Part 2: The Beginnings {.unnumbered}

  - **Starting a project:** Importing data 

  - **Basic functionality:** Logic and shortcuts
  
  - **Several methods for calling different variables** Calling data with operators
  
  - **Getting fancy widdit:** What are functions, packages, and how can we use them? 
  
  - **Coding etiquette:** How to write simple and reproducible code

### Part 3: Buckle up {.unnumbered}

  - **Data wrangling:** Data wrangling with base R and other important packages
 



